using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Broiler.Documents.Office;

/// <summary>
/// One pattern struck out of a seed's text before the text is compared, and the
/// argument for striking it.
/// </summary>
/// <remarks>
/// <para>
/// The reason is not decoration. This is the only row in the manifest that can
/// hide a real failure, so it does not get to exist without something a person
/// can disagree with attached to it. The ordinary answer to a difference between
/// two targets is a baseline row somebody has to classify; an ignore is for the
/// narrower case where the text a comparison would see was generated by the
/// reading application rather than written by the author, and so could never be
/// classified as anything.
/// </para>
/// </remarks>
internal sealed record TextIgnore(string Pattern, string Why)
{
    /// <summary>
    /// Removes what this exception covers, from both sides of a comparison.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Applied to both projections rather than to one, because the exception
    /// exists to say "neither implementation is wrong about this", not "believe
    /// LibreOffice". Applying it to one side would silently make the other side
    /// the reference.
    /// </para>
    /// <para>
    /// It is deliberately per seed and deliberately carries a <c>Why</c> that
    /// the schema requires. The alternative - widening the global
    /// canonicalisation until the noisy document goes quiet - buys the same
    /// green run at the cost of hiding the same class of difference in every
    /// other document, which is the trade a suite like this exists to refuse.
    /// </para>
    /// </remarks>
    public string Apply(string text) =>
        System.Text.RegularExpressions.Regex.Replace(
            text, Pattern, string.Empty,
            System.Text.RegularExpressions.RegexOptions.None,
            TimeSpan.FromSeconds(5));
}

/// <summary>
/// What a seed asserts about the documents made from it.
/// </summary>
/// <remarks>
/// <para>
/// Both fields are deliberately coarse, and the coarseness is the point. Where a
/// line wraps depends on the host's font metrics and where a page ends depends
/// on a typesetting program this project does not own, so an expectation stated
/// as an exact page count or a width in pixels would fail on the leg that was
/// working perfectly. A floor and a boolean are what can be asserted about every
/// host, which is less than a reader might want and all that is true.
/// </para>
/// </remarks>
/// <param name="MinParagraphs">
/// A floor rather than a count. Whether a list item, a heading or a table cell
/// is a paragraph is answered differently by each target, so this is set to the
/// number every target has to agree on and no higher.
/// </param>
/// <param name="Multipage">
/// Whether the seed is asserted to produce more than one page. Only two seeds
/// claim it, by the two routes that do not depend on the host: one says so in
/// the document with an explicit break, and one is long enough that the page
/// runs out several times over on any machine honouring the stated box. A seed
/// that merely hoped to overflow would be an assertion about the host's fonts
/// wearing a document's clothes, which is why there is no third.
/// </param>
/// <param name="SubstitutesFonts">
/// Whether the seed knowingly asks for glyphs no pinned family has. It degrades
/// the font guard for this seed to a skip naming the seed's own reason, because
/// reporting a substitution nobody could have avoided as a failure would teach a
/// reader to ignore the one guard that catches the substitutions that matter.
/// </param>
internal sealed record OfficeExpectation(int MinParagraphs, bool Multipage, bool SubstitutesFonts);

/// <summary>
/// One authored HTML fragment, and everything the suite knows about it before
/// LibreOffice has been asked to do anything with it.
/// </summary>
/// <remarks>
/// <para>
/// The seed is markup held as a string rather than a document on disk, and that
/// is not a convenience. No document of a supported format is committed to this
/// repository - a guard walks the whole tree and fails the build over one - so a
/// corpus that needed a .docx to start from could only get it by downloading it,
/// which is the same act with the evidence deleted. The runner writes the seed
/// into a temporary workspace, asks LibreOffice to rewrite it into each target,
/// and throws the workspace away, so the only durable artefact of a run is the
/// report it printed.
/// </para>
/// <para>
/// HTML is the input because it is the one format that can be written as a
/// string in a manifest, read by the office suite without a converter of this
/// project's own standing in the way, and reviewed by a person looking at a
/// diff. That last property is why the markup is kept on one line: a seed is
/// read beside the seed next to it far more often than it is read on its own.
/// </para>
/// </remarks>
internal sealed record OfficeSeed(
    string Id,
    string Why,
    string Html,
    OfficeExpectation Expect,
    IReadOnlyList<TextIgnore> TextIgnore);

/// <summary>
/// The seed corpus, as <c>tests/office/office-corpus.json</c> states it.
/// </summary>
/// <remarks>
/// <para>
/// Read with <see cref="JsonDocument"/> rather than through a serializer, which
/// is the choice <c>CorpusManifest</c> already made for the other corpus and is
/// worth keeping for one reason: the failure a manifest actually produces is a
/// field that is present and wrong, not a field of the wrong CLR type, and the
/// message a person needs then names the seed rather than a JSON path. Reading
/// by hand costs a few lines and buys every one of those messages.
/// </para>
/// </remarks>
internal sealed class OfficeManifest
{
    /// <summary>Where the manifest lives, for a caller that has a repository root and no path.</summary>
    public const string RelativePath = "tests/office/office-corpus.json";

    /// <summary>
    /// The formats this component composes, which is what a target is checked
    /// against.
    /// </summary>
    /// <remarks>
    /// Markdown is in the list although no seed targets it. The check being made
    /// here is that a target names a format this component knows - not that it
    /// names one an office suite can export, which is a fact about an external
    /// tool. A tool that cannot write a target is a skip with a reason at run
    /// time, never an exception at load time and never a silent pass.
    /// </remarks>
    public static readonly IReadOnlyList<string> KnownFormats =
        ["docx", "odt", "rtf", "html", "md"];

    /// <summary>
    /// Every family reference the manifest is allowed to write, in the one
    /// spelling the schema permits.
    /// </summary>
    /// <remarks>
    /// Two expressions rather than one because they answer different questions.
    /// The first collects the families that were named and can therefore be
    /// checked; the second finds every place a family was declared at all. The
    /// second exists only to catch the declarations the first one missed - an
    /// unquoted name, or a quoting style nobody agreed on - because a family
    /// this loader silently skipped is a family nobody checked against the
    /// pinned set, and a check that quietly examines less than it was asked to
    /// reads exactly like a check that passed.
    /// </remarks>
    private static readonly Regex QuotedFamily =
        new("font-family:'([^']*)'", RegexOptions.CultureInvariant);

    private static readonly Regex AnyFamily =
        new("font-family:", RegexOptions.CultureInvariant);

    private OfficeManifest(
        IReadOnlyList<string> fonts,
        IReadOnlyList<string> toolFonts,
        IReadOnlyList<string> targets,
        IReadOnlyList<OfficeSeed> seeds)
    {
        Fonts = fonts;
        ToolFonts = toolFonts;
        Targets = targets;
        Seeds = seeds;
    }

    /// <summary>
    /// The families a seed may name. Pinned because LibreOffice substitutes a
    /// missing family in silence: a document asking for a face the host does not
    /// have is drawn with whatever the host picked, and every measurement taken
    /// from it afterwards measures the substitute.
    /// </summary>
    public IReadOnlyList<string> Fonts { get; }

    /// <summary>
    /// Faces the office suite supplies rather than any seed naming them.
    /// </summary>
    /// <remarks>
    /// LibreOffice draws a list bullet from its own symbol font, and a host may
    /// offer a substitute for that font in turn. Neither arrives because a
    /// document asked for it, so a font guard that refused them would fail every
    /// seed containing a bullet - which is to say, a guard nobody could leave
    /// switched on.
    /// </remarks>
    public IReadOnlyList<string> ToolFonts { get; }

    /// <summary>The formats LibreOffice is asked to rewrite each seed into.</summary>
    public IReadOnlyList<string> Targets { get; }

    /// <summary>The seeds, in the order the manifest lists them.</summary>
    public IReadOnlyList<OfficeSeed> Seeds { get; }

    public static OfficeManifest Load(string path)
    {
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(path));
        JsonElement root = document.RootElement;

        int version = root.GetProperty("schemaVersion").GetInt32();
        if (version != 1)
        {
            throw new InvalidDataException(
                "office-corpus.json declares schemaVersion " +
                version.ToString(CultureInfo.InvariantCulture) +
                ", which this runner does not know how to read.");
        }

        var fonts = root.GetProperty("fonts").EnumerateArray()
            .Select(font => font.GetString() ?? string.Empty).ToArray();

        var toolFonts = root.TryGetProperty("toolFonts", out JsonElement tools)
            ? tools.EnumerateArray().Select(font => font.GetString() ?? string.Empty).ToArray()
            : [];

        var targets = root.GetProperty("targets").EnumerateArray()
            .Select(target => target.GetString() ?? string.Empty).ToArray();

        var seeds = root.GetProperty("seeds").EnumerateArray().Select(seed =>
        {
            JsonElement expect = seed.GetProperty("expect");
            return new OfficeSeed(
                Text(seed, "id"),
                Text(seed, "why"),
                Text(seed, "html"),
                new OfficeExpectation(
                    expect.GetProperty("minParagraphs").GetInt32(),
                    expect.GetProperty("multipage").GetBoolean(),
                    expect.TryGetProperty("substitutesFonts", out JsonElement substitutes) &&
                    substitutes.GetBoolean()),
                seed.TryGetProperty("textIgnore", out JsonElement ignores)
                    ? ignores.EnumerateArray()
                        .Select(item => new TextIgnore(Text(item, "pattern"), Text(item, "why")))
                        .ToArray()
                    : []);
        }).ToArray();

        var manifest = new OfficeManifest(fonts, toolFonts, targets, seeds);
        manifest.Validate();
        return manifest;
    }

    /// <summary>
    /// The checks the JSON schema cannot make, and the reason each of them is
    /// here rather than there.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The split is not arbitrary and it is worth stating, because the obvious
    /// reading - that the schema does shapes and the loader does everything else
    /// - is wrong in both directions. The schema owns what can be decided by
    /// looking at one value: the identifier's spelling, a non-empty
    /// <c>why</c>, the page box and the body font a seed's markup must state,
    /// and the pinned family names, which it holds as an enum of its own. What
    /// it cannot express is any statement about one part of the instance
    /// agreeing with another, because a schema has no way to reach across an
    /// instance and compare.
    /// </para>
    /// <para>
    /// So the five checks below are exactly the cross-field ones. Two ids are
    /// each fine on their own and wrong together, and the same id twice would
    /// overwrite a row in the report rather than fail. A family named in markup
    /// is checked here against <em>this manifest's</em> <c>fonts</c> array,
    /// which the schema can only approximate against its own fixed list - so a
    /// manifest that shortened its font list would still pass the schema and
    /// fails here. A target is checked against the formats this component
    /// composes, which live in code and not in the file. And a
    /// <c>textIgnore</c> pattern is compiled with the engine that will actually
    /// run it, because <c>format: regex</c> is an annotation most validators do
    /// not enforce, and a pattern that throws at comparison time reports itself
    /// as a failure of the seed rather than of the manifest.
    /// </para>
    /// <para>
    /// Every problem is collected before any is thrown. A loader that failed on
    /// the first one would make a person fix twelve seeds in twelve runs, and
    /// the message names the seed in each case because the seed is what they
    /// have to open.
    /// </para>
    /// </remarks>
    public void Validate()
    {
        var problems = new List<string>();
        var fonts = Fonts.ToHashSet(StringComparer.Ordinal);
        var known = KnownFormats.ToHashSet(StringComparer.Ordinal);

        // Ids reach the report and the --only filter, where two rows with the
        // same name would quietly overwrite one another rather than fail.
        foreach (string duplicate in Seeds.Select(seed => seed.Id)
                     .GroupBy(id => id, StringComparer.Ordinal)
                     .Where(group => group.Count() > 1)
                     .Select(group => group.Key))
        {
            problems.Add("Two seeds share the id " + duplicate + ".");
        }

        foreach (string target in Targets)
        {
            if (!known.Contains(target))
            {
                problems.Add(
                    "The targets list names a format this component does not compose: " +
                    target + ". The known formats are " + string.Join(", ", KnownFormats) + ".");
            }
        }

        foreach (OfficeSeed seed in Seeds)
        {
            if (string.IsNullOrWhiteSpace(seed.Html))
            {
                problems.Add(
                    seed.Id + " carries no html, so there is nothing to hand the office suite. " +
                    "A seed with no markup would materialise an empty document and pass every " +
                    "check in the suite that is not about a construct.");
            }

            foreach (TextIgnore ignore in seed.TextIgnore)
            {
                try
                {
                    _ = new Regex(ignore.Pattern, RegexOptions.CultureInvariant);
                }
                catch (ArgumentException error)
                {
                    problems.Add(
                        seed.Id + " has a textIgnore pattern that does not compile: " +
                        ignore.Pattern + " - " + error.Message);
                }
            }

            MatchCollection quoted = QuotedFamily.Matches(seed.Html);
            var readable = quoted.Select(match => match.Index).ToHashSet();

            // Quoting the offending text rather than counting it. A count would
            // say that one of three declarations could not be read and leave
            // the reader to find which; the markup itself says which, and the
            // spelling is usually the whole of the answer.
            foreach (Match declaration in AnyFamily.Matches(seed.Html))
            {
                if (readable.Contains(declaration.Index))
                    continue;

                int length = Math.Min(48, seed.Html.Length - declaration.Index);
                problems.Add(
                    seed.Id + " writes a font family this loader cannot read, at: " +
                    seed.Html.Substring(declaration.Index, length) +
                    " - the single-quoted form is the only spelling the schema permits, and a " +
                    "family the loader skipped is a family nobody checked against the pinned set.");
            }

            foreach (string family in quoted
                         .Select(match => match.Groups[1].Value)
                         .Distinct(StringComparer.Ordinal))
            {
                if (!fonts.Contains(family))
                {
                    problems.Add(
                        seed.Id + " names a font the fonts list does not pin: " + family +
                        ". LibreOffice substitutes a missing family without saying so, so a " +
                        "seed asking for it would measure the host's fonts and look like a " +
                        "seed that passed.");
                }
            }
        }

        if (problems.Count > 0)
            throw new InvalidDataException("office-corpus.json does not hang together:\n  " + string.Join("\n  ", problems));
    }

    private static string Text(JsonElement element, string name) =>
        element.GetProperty(name).GetString()
        ?? throw new InvalidDataException("office-corpus.json has a null where " + name + " must be a string.");
}
