using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Broiler.Documents.Pdf.Tests.Fuzzing;

/// <summary>
/// What a campaign found, in the shape §6.6 requires a minimized failure to be
/// recorded in.
/// </summary>
/// <remarks>
/// The input itself is not in the record. A campaign runs on generated bytes
/// today and could later run on a corpus whose rights are decided per artifact,
/// so a record that embedded its input would carry an artifact past the decision
/// that governs it. The hash identifies it; the seed reproduces it.
/// </remarks>
public sealed record FuzzFailure
{
    public required string InputSha256 { get; init; }

    /// <summary>Reproduces the input exactly, given the same harness version.</summary>
    public required ulong Seed { get; init; }

    public required string Target { get; init; }

    public required string HarnessVersion { get; init; }

    /// <summary>Which limits produced this; the same bytes under looser ones are a different result.</summary>
    public required string LimitProfile { get; init; }

    /// <summary>What went wrong, in a form a triager can group by.</summary>
    public required string FailureClass { get; init; }

    public required int InputLength { get; init; }

    /// <summary>
    /// Where the input came from, for the rights question §6.6 asks of every
    /// retained artifact.
    /// </summary>
    public required string CorpusRights { get; init; }

    public override string ToString() =>
        $"{Target} {FailureClass} seed={Seed} sha256={InputSha256[..16]}… " +
        $"len={InputLength} profile={LimitProfile} rights={CorpusRights}";
}

/// <summary>
/// Runs a fuzz target over generated inputs and reports what it could not
/// survive.
/// </summary>
/// <remarks>
/// <para>
/// <strong>This is a mutation campaign, not a coverage-guided one.</strong> It
/// generates from a seed and mutates a corpus of its own making; it has no
/// coverage feedback, so it explores by luck rather than by measurement.
/// §6.6 wants coverage-guided campaigns nightly, and that needs an instrumenting
/// engine — which is itself a tool needing a manifest row and a licence review
/// before CI may run it. The harness is shaped so that engine drops in: a target
/// is <c>Action&lt;ReadOnlySpan&lt;byte&gt;&gt;</c>, which is the signature every
/// such engine drives.
/// </para>
/// <para>
/// Deterministic on purpose. A campaign that cannot be replayed produces
/// failures nobody can reproduce, so every input traces to a seed and the seed is
/// in the record.
/// </para>
/// </remarks>
public sealed class FuzzCampaign
{
    /// <summary>Bumped whenever generation changes, because seeds stop meaning the same thing.</summary>
    public const string HarnessVersion = "1";

    /// <summary>
    /// Exceptions a parser is allowed to fail with. Everything else is a finding.
    /// </summary>
    /// <remarks>
    /// One entry, and that is the point. ADR 0003/0004 say a read reports
    /// malformed input through its result rather than by throwing, so for these
    /// targets <em>any</em> exception is a finding — including the plausible
    /// ones. A list that admitted FormatException would have let the reader
    /// throw where its own contract says it reports, and nothing would have
    /// noticed.
    /// </remarks>
    private static bool IsExpected(Exception exception) => exception is OperationCanceledException;

    private readonly Action<ReadOnlySpan<byte>> _target;
    private readonly string _name;

    public FuzzCampaign(string name, Action<ReadOnlySpan<byte>> target)
    {
        _name = name ?? throw new ArgumentNullException(nameof(name));
        _target = target ?? throw new ArgumentNullException(nameof(target));
    }

    /// <summary>
    /// Runs until <paramref name="iterations"/> inputs have been tried or
    /// <paramref name="budget"/> elapses, whichever comes first.
    /// </summary>
    /// <remarks>
    /// The time budget is what makes this usable both as a pull-request check of
    /// a few seconds and as a nightly campaign of half an hour, without two
    /// different harnesses drifting apart.
    /// </remarks>
    public IReadOnlyList<FuzzFailure> Run(ulong seed, int iterations, TimeSpan budget)
    {
        var failures = new List<FuzzFailure>();
        var clock = Stopwatch.StartNew();
        var random = new SplitMix64(seed);

        for (int i = 0; i < iterations && clock.Elapsed < budget; i++)
        {
            ulong inputSeed = random.Next();
            byte[] input = Generate(inputSeed);

            try
            {
                _target(input);
            }
            catch (Exception ex) when (IsExpected(ex))
            {
                // A refusal. That is the parser working.
            }
            catch (Exception ex)
            {
                failures.Add(new FuzzFailure
                {
                    InputSha256 = Convert.ToHexStringLower(SHA256.HashData(input)),
                    Seed = inputSeed,
                    Target = _name,
                    HarnessVersion = HarnessVersion,
                    LimitProfile = FuzzTargets.LimitProfileName,
                    FailureClass = ex.GetType().Name,
                    InputLength = input.Length,
                    CorpusRights = "generated-in-code; no third-party artifact, no rights decision required",
                });
            }
        }

        return failures;
    }

    /// <summary>Rebuilds one campaign input from its recorded seed.</summary>
    public static byte[] Reproduce(ulong inputSeed) => Generate(inputSeed);

    /// <summary>
    /// One input: a PDF skeleton with parts of it corrupted.
    /// </summary>
    /// <remarks>
    /// Purely random bytes are rejected at the header and exercise almost
    /// nothing, so generation starts from something PDF-shaped and damages it.
    /// That is the difference between fuzzing a parser and fuzzing its front
    /// door.
    /// </remarks>
    private static byte[] Generate(ulong inputSeed)
    {
        var random = new SplitMix64(inputSeed);
        byte[] skeleton = Skeleton(random);

        int mutations = 1 + (int)(random.Next() % 24);
        for (int i = 0; i < mutations; i++)
        {
            int at = (int)(random.Next() % (ulong)skeleton.Length);
            switch (random.Next() % 4)
            {
                case 0:
                    skeleton[at] = (byte)random.Next();
                    break;
                case 1:
                    skeleton[at] ^= (byte)(1 << (int)(random.Next() % 8));
                    break;
                case 2:
                    // Truncation, which is the shape most parsers get wrong.
                    return skeleton[..Math.Max(1, at)];
                default:
                    skeleton[at] = (byte)"0123456789 <<>>/[]()"[(int)(random.Next() % 20)];
                    break;
            }
        }

        return skeleton;
    }

    /// <summary>A small well-formed PDF, varied enough that seeds differ.</summary>
    private static byte[] Skeleton(SplitMix64 random)
    {
        int pages = 1 + (int)(random.Next() % 3);
        var text = new StringBuilder("%PDF-1.7\n");
        text.Append("1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n");
        text.Append("2 0 obj<</Type/Pages/Count ").Append(pages).Append("/Kids[");
        for (int i = 0; i < pages; i++)
            text.Append(3 + i).Append(" 0 R ");
        text.Append("]>>endobj\n");

        for (int i = 0; i < pages; i++)
        {
            text.Append(3 + i).Append(
                " 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents ")
                .Append(3 + pages + i).Append(" 0 R>>endobj\n");
        }

        for (int i = 0; i < pages; i++)
        {
            string stream = "BT /F1 12 Tf 72 720 Td (page " +
                (i + 1).ToString(CultureInfo.InvariantCulture) + ") Tj ET";
            text.Append(3 + pages + i).Append(" 0 obj<</Length ")
                .Append(stream.Length).Append(">>stream\n").Append(stream).Append("\nendstream endobj\n");
        }

        text.Append("trailer<</Size ").Append(3 + pages * 2).Append("/Root 1 0 R>>\n");
        text.Append("startxref\n0\n%%EOF");
        return Encoding.ASCII.GetBytes(text.ToString());
    }

    /// <summary>
    /// A small, fast, fully specified generator, so a seed means the same thing
    /// on every machine and every runtime.
    /// </summary>
    /// <remarks>
    /// <c>System.Random</c> is explicitly not guaranteed stable across runtime
    /// versions, which would silently break every recorded seed on an upgrade.
    /// </remarks>
    private struct SplitMix64(ulong state)
    {
        private ulong _state = state;

        public ulong Next()
        {
            _state += 0x9E3779B97F4A7C15UL;
            ulong z = _state;
            z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9UL;
            z = (z ^ (z >> 27)) * 0x94D049BB133111EBUL;
            return z ^ (z >> 31);
        }
    }
}
